name: Android Master CI

on:
  push:
    branches:
      - 'master'

jobs:
     
  apk:
    name: Generate APK
    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v1
      - name: set up JDK 1.11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Get NDK 
        run: sudo ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;21.0.6113669"
      - name: Build Release APK
        run: bash ./gradlew assembleStandardRelease --stacktrace
      - name: Sign Android release
        uses: r0adkll/sign-android-release@v1
        with:
          # The directory to find your release to sign
          releaseDirectory: app/build/outputs/apk/standard/release
          # The key used to sign your release in base64 encoded format
          signingKeyBase64: "dfdsfsdfsfdfs"
      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: TachiyomiAZ-${{ github.sha }}.apk
          path: ${{ env.SIGNED_RELEASE_FILE }}
